version: '3'

services:
  web: 
    build: .

    image: node:20
    depends_on: 
      - db

    ports:
      - "3000:3000"

    environment:
      DATABASE_URL: "postgres://'user':'password'@localhost:5432/api_name"
      NODE_ENV: "development"

    networks:
      - postgres-in

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "49555:5432"

    networks:
      - postgres-in

networks:
  postgres-in:
    driver: bridge